Feat/add biancarosa changes
stone-payments/cert-manager-webhook-dyndns pull request #1
Opened 2020-10-27 14:26 UTC by csmartins

2020-10-27 15:27 UTC, haooliveira84 requested changes

2020-10-27 15:27 UTC, haooliveira84 commented on deploy/cert-manager-webhook-dyndns/templates/deployment.yaml
> +apiVersion: apps/v1beta1
```suggestion
apiVersion: apps/v1
```

2020-11-03 15:59 UTC, biancarosa approved these changes

2020-11-03 16:00 UTC, haooliveira84 approved these changes

2020-11-03 16:00 UTC, merged